(function() {
  'use strict'

  angular.module('einstock.machine', [
      'ngMaterial'
    ])
    .controller('MachineController', MachineController)

  MachineController.$inject = ['$scope'];

  //Welcome controller for static welcome page
  function MachineController($scope) {
    $scope.about = "Machine learning is a type of artificial intelligence (AI) that provides computers with the ability to learn without being explicitly programmed. Machine learning focuses on the development of computer programs that can teach themselves to grow and change when exposed to new data.";
    $scope.algoIntro = "The Einstoc app utilizes a wide range of cutting-edge machine learning algorithms in our predictions of the stock market, including:";
    $scope.typesummary = "Machine learning tasks are typically classified into three broad categories, depending on the nature of the learning signal or feedback available to a learning system. These are:";
    $scope.types = ["Supervised learning: The computer is presented with example inputs and their desired outputs, given by a teacher, and the goal is to learn a general rule that maps inputs to outputs.", "Unsupervised learning: No labels are given to the learning algorithm, leaving it on its own to find structure in its input. Unsupervised learning can be a goal in itself (discovering hidden patterns in data) or a means towards an end (feature learning).", "Reinforcement learning: A computer program interacts with a dynamic environment in which it must perform a certain goal (such as driving a vehicle), without a teacher explicitly telling it whether it has come close to its goal. Another example is learning to play a game by playing against an opponent."];
    $scope.algoTitles = ['K Nearest Neighbors (KNN)','Logistic Regression (LR)','Naive Bayes (NB)','Neural Networks (NN)','Random Forests (RF)','Support Vector Machine (SVM)'];
    $scope.algorithms = ['The KNN algorithm is a non-parametric method for classification and regression. The algorithm takes a large quantity of training data, which include vectors of multi-dimentional features/predictors and class labels (the correct outcome). To classify an new, unlabeled vector, the algorithm finds the k datapoints in the training sample that are cloest to the unlabeled vector, and assign the most common label among the k cloest "neighbors" as the classification for the unlabeled datapoint.','Logistic regression is one of the most popular machine learning method for binary classification. LR uses training data to estimate the odds of being a case. The odds are defined as the probability that a particular outcome is a case divided by the probability that it is a noncase. Like other regression methods, LR uses an linear equation as the model representation. the model coeffiicents are then estimated using maximum-likelihood method.',"Naive Bayes classifiers are a family of simple probabilistic classifiers based on applying Bayes' theorem with strong (naive) independence assumptions between the features.",'Neural networks are a machine learning approach that is based on a large collection of "neural units" loosely modeling the way the brain solves problems with large clusters of biological neurons connected by axons. Each neural unit is connected with many others, and links can be enforcing or inhibitory in their effect on the activation state of connected neural units. An NN is typically defined by three types of parameters: \n1. The interconnection pattern between the different layers of neurons; \n2. The learning process for updating the weights of the interconnections; \n3. The activation function that converts a neuron\'s weighted input to its output activation. \nThe network then try to find the optimal solution that matches the features of the datapoint under examination by processing a large quantity of training data to detect patterns.','Random forests is an ensemble learning method for classification and regression. It operates by creating a multitude of decision trees at the training phase. The classification prediction the algorithm outputs is a composition of the predictions by individual trees.','The SVM model algorithm maps the training data into points in space, so that datapoints from separate categories are divided by a clear gap that is as wide as possible. New datapoints are then mapped into that same space and predicted to belong to a category based on which side of the gap they fall on. In addition to performing linear classification, SVMs can efficiently perform a non-linear classification using the kernel method, implicitly mapping their inputs into high-dimensional feature spaces.'];
    $scope.methods = "";
  }
})();
